# Generated by Django 5.0.4 on 2025-04-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20240312_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ForestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', models.FloatField()),
                ('area', models.FloatField()),
                ('density', models.FloatField()),
                ('change', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='mainapp.forest')),
            ],
            options={
                'unique_together': {('forest', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='CreditBalance',
        ),
        migrations.DeleteModel(
            name='ImageHistory',
        ),
        migrations.DeleteModel(
            name='PaymentsActivated',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
